{% set name = "libcxx" %}
{% set version = "3.9.1" %}
{% set sha256 = "25e615e428f60e651ed09ffd79e563864e3f4bc69a9e93ee41505c419d1a7461" %}

{% set libcxx_variant = os.environ.get('LIBCXX_VARIANT', 'default') %}
{% set build_number = "1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.src.tar.xz
  url: http://llvm.org/releases/{{ version }}/{{ name }}-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  number: {{ build_number }}
  string: {{ libcxx_variant }}_{{ build_number }}
  skip: true  # [(unix and py<36) or win]
{% if libcxx_variant == "cling" %}
  features:
    - cling
    - vc14     # [win and py36]
{% else %}
  features:    # [win and py36]
    - vc14     # [win and py36]
{% endif %}

requirements:
  build:
    - toolchain
    - cmake >=3.4.3
    # Needed to unpack the source tarball
    - m2-xz  # [py27 and win32]
    - m2w64-xz  # [py27 and win64]

    - system  # [linux and not armv7l]

    # "compiling .pyc files" fails without this:
    - python                                # [not win]
    - python {{ environ['PY_VER'] + '*' }}  # [win]

    - clangdev =={{ version }}
    - gcc-6  # [linux]
    - binutils >=2.28  # [linux]

  run:
    - system  # [linux and not armv7l]
    - clangdev =={{ version }}
    - libgcc-6  # [linux]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}  # [win]
{% if libcxx_variant == "cling" %}
    - cling-patches
{% endif %}

  commands:
    - if not exist %LIBRARY_INC%\\c++\\v1\\iterator exit 1     # [win]

    - test -f $PREFIX/include/c++/v1/iterator      # [unix]

about:
  home: http://llvm.org/
  license: NCSA
  license_file: LICENSE.TXT
  summary: C++ standard library

extra:
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - mattwala
